CNN feature extractor:
Can use popular encoder architectures:
-  VGG16 ResNet-50 MobileNet

Decoder section:
FCN-32, 16, 8 

Pooling layer reminder:
image 4, 2 x pooling 2, 2 with stride of 2 => 2, 1

FCN 32 upsample 2**5 times the encoded image  
FNC 16 is based on FCN32 but also uses Pool4 = 1/2**4 Downsampled Encoded Image (second to last pooling layer)  
    - 1st step: output_1  = Upsampling of Pool5 by 2 (shape: 2 x shape of Pool5)  
    - 2nd step: output_2 = pixel wise prediction by 1-1 conv to do the pool4 result (shape: shape of pool 4)  
    => Upsampling of sum(output_1 + output_2) by 16  

FCN 8: Same as FCN16 but upsamples the (output_1, output_2) by 2 = output_3  
    - output_4 = sum(pixel wise prediction on pool3)  
    => Upsampling of sum(output_3 + output_4)  

Upsampling in tensorflow
Upsample2D:
    Params: scaling: how to choose the value of the 
    Nearest(closest neighboor value), bilinear (avg of the neighboors)
Transposed convolution


In [1]:
import tensorflow as tf

2022-12-02 06:14:22.571282: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [12]:
a = tf.ones(
    shape=(1, 56, 56, 256)
)

In [17]:
import numpy as np

In [19]:
tf.keras.backend.mean(a, axis=(0, 1, 2)).numpy()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [20]:
np.squeeze(
    tf.keras.backend.mean(a, axis=(0, 1, 2)).numpy()
) == tf.keras.backend.mean(a, axis=(0, 1, 2)).numpy()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [9]:
tf.squeeze(a)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 3],
       [1, 4]], dtype=int32)>

In [2]:
tf.keras.layers.UpSampling2D(size=(2,2), data_format=None, interpolation='nearest') # interpolation = scaling

In [ ]:
#Transposed convolution
# Reverse of convolution
# Prediction of the pixel that would have led to the convoluted result

# tf.keras.layers.Conv2DTranspose(filters, kernel_size, strides)

In [ ]:
# conv2d (1, 1)
#handy and quick way to convert the dimensionsof the output of the previous layer
# dont forget the cropping layer

In [ ]:
# Evaluation of segmation

# Area_of_overlap = Count/sum(true positives)
# Combined_Area = Total pixel in predicted segmentation mask + total pixels in true segmentation mask

# A of union Combined - Overlap

# defining metrics
# IoU = intersection / union => help understanding worst case performance

# Dice score: 2 (Overlap / Combined) => understanding average performance

In [ ]:
# Unet:
# Skip connections between envoder and decoder

# Econder path: similair to FCN (Convolutional Downsampling) Maxpooling (2, 2) is responsible of the downsampling
# Addition bootleneck Conv2D (without pooling) layers to extract more features

# Decoder
# bottleneck Upsampling (Upsample0) from (8, 8) to (512, 16, 16)

# Output(Pool4): shape(512, 16, 16) and Output(Upsample0) have the same shape (and are at the same level of the U shape)

# Concat([output(pool4), output(upsample0)]) = (1024, 16, 16) => Conv2D = (512, 16, 16) => Conv2D = (256, 16, 16) 
# (skip connections from encoder to decoder + Additional conv layer to reduce the concat dimensionality)

# 1, 1 convolutions for prediction
